[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/api/openai/create"
  function = "openai-create"

[[edge_functions]]
  path = "/api/openai/status"
  function = "openai-status"